- hosts: localhost
  become: true
  tasks:
  - name: Install htop
    apt: name=htop

  - name: Install git
    apt: name=git

  - include: tasks/gnome.yml

  -  script: tasks/java.sh

  -  script: tasks/netbeans.sh
